apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app: jmeter
    name: influxdb
  name: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 11Gi

