apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: influxdb-1x
  name: influxdb-1x
  namespace: perftest
spec:
  ports:
    - name: 8086-tcp
      port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    deploymentconfig: influxdb-1x
  sessionAffinity: None
  type: ClusterIP

