apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-branch: master
    fabric8.io/git-commit: 9a41048f1170bcf792cfdfa8f7059e788b018518
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=camel-amq-fakeapp&var-version=1.0-SNAPSHOT
  creationTimestamp: null
  generation: 1
  labels:
    app: camel-amq-fakeapp
    group: org.fgiloux.sandbox
    provider: fabric8
    version: 1.0-SNAPSHOT
  name: camel-amq-fakeapp
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: camel-amq-fakeapp
    group: org.fgiloux.sandbox
    provider: fabric8
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 3600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/git-branch: master
        fabric8.io/git-commit: 9a41048f1170bcf792cfdfa8f7059e788b018518
        fabric8.io/iconUrl: img/icons/camel.svg
        fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=camel-amq-fakeapp&var-version=1.0-SNAPSHOT
      creationTimestamp: null
      labels:
        app: camel-amq-fakeapp
        group: org.fgiloux.sandbox
        provider: fabric8
        version: 1.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SPRING_CONFIG_LOCATION
          value: /deployments/configuration/application.properties
        - name: amqp.options.transport.trustStorePassword
          valueFrom:
            secretKeyRef:
              name: app-broker-jks
              key: amqp.options.transport.trustStorePassword
        - name: JAEGER_SERVICE_NAME
          value: fakeapp
        - name: JAEGER_SAMPLER_PARAM
          value: '1.0'
        - name: JAEGER_PROPAGATION
          value: 'jaeger,b3'
        image: docker-registry.default.svc:5000/perftest/camel-amq-fakeapp
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: fake-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /deployments/configuration
          name: app-properties
        - mountPath: /opt/broker-jks
          name: app-broker-jks
      - image: jaegertracing/jaeger-agent
        name: jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        args:
          - '--collector.host-port=jaeger-collector.perftest.svc:14267'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: camel-amq-fakeapp-props
        name: app-properties
      - name: app-broker-jks
        secret:
          defaultMode: 420
          secretName: app-broker-jks
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - fake-app
      from:
        kind: ImageStreamTag
        name: camel-amq-fakeapp:latest
        namespace: perftest
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
